# Generated by Django 4.1.7 on 2023-03-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('BLB', 'Blueberry'), ('VAN', 'Vanilla'), ('CHO', 'Chocolate'), ('STR', 'Strawberry'), ('BAN', 'Banana'), ('MNG', 'Mango')], max_length=3)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_vegan', models.BooleanField()),
                ('is_gluten_free', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.store')),
            ],
        ),
    ]
